# Generated by Django 4.1.6 on 2023-02-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_to_do',
            field=models.TextField(help_text='YYYY-mm-dd', max_length=10, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_process', 'В процессе'), ('done', 'Сделано')], default='new', max_length=30, verbose_name='Статус'),
        ),
    ]
